### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by CerebralDatabank**
Made some small changes:

- Fixed the "chopped off" left and right side of MAES logo in header
  - Image size changed from 585×585 to 605×605 (20-pixel extension on each edge)
- Made max width of page content `1000px` to make app easier to use on very wide screens
  - Also put page content in a `<main>` tag, which will help with accessibility
- Added a CSS variable for main MAES color in `application.css`
  - When merging later, we can use this for page & button background colors, etc. instead of repeating the exact color everywhere

### CODE REVIEW

**Review by jhbeeber — APPROVED** [review]
LGTM! Having a set CSS color will probably be really useful when we attempt to test it for usability. Also, the logo looks nice!

**Review by ShahirAliGit — APPROVED** [review]
LGTM

**Review by annapachecohartman — APPROVED** [review]
Nice job with logo! These changes are great for the styling

**Review by jaejin0 — APPROVED** [review]
Looking great!

**Pull request merged**
