### PR TITLE
Tests for transaction history in officer view

### PR DESCRIPTION
**Pull request by CerebralDatabank**
Testing:

- Making user complete activity and ensuring it shows in transaction history
- Spending points as user and ensuring it shows in transaction history

### CODE REVIEW

**Comment by CerebralDatabank** [comment]
Passes but with lower code coverage. I'm not sure if the code coverage will improve after merging.

image

**Review by annapachecohartman — APPROVED** [review]
Looks good, just fix rubocop so that it passes on Github.

**Review by jhbeeber — APPROVED** [review]
Looks good at a glance. At the worst, I think the code coverage would stay the same.

**Comment by CerebralDatabank** [comment]
Fixed the Rubocop offenses.

image

**Comment by CerebralDatabank** [comment]
Fixed Rubocop (again).

RSpec
image

Rubocop
image

**Pull request merged**
