### PR TITLE
Finished skeleton of CRUD for rewards/merchanise

### PR DESCRIPTION
**Pull request by annapachecohartman**
Functionality for creating new reward, viewing all rewards, detailed view for each reward, editing, and deleting - all encompassed within the "admin view" . "member view" entails viewing the rewards and purchasing them.  No CSS styling implemented yet.

### CODE REVIEW

**Review by CerebralDatabank — CHANGES_REQUESTED** [review]
Added some stuff for flash notices and fixed indents (used `:notice` for success messages and `:alert` for error messages). Please check to make sure I did it correctly :)

Also check:

- Blank values are permitted when adding a new reward; in fact, a reward can be created with blank values for everything by just clicking "Create"
- Putting an out of bounds value into the Points field leads to a Rails error screen (should be a flash notice)
  image
- Successfully editing a reward should lead to that reward's details page instead of the rewards home page

**Comment by annapachecohartman** [comment]
I made the changes - when creating a reward, all values should be filled out. Also, point and dollar values should be within acceptable limits. After editing a reward, the user is redirected to the reward's details page. Please note that the two commits by "root" are by me. I resolved the issue.

**Review by CerebralDatabank — CHANGES_REQUESTED** [review]
Did some small formatting stuff so make sure you pull again 😅

Only one remaining issue — bounds check is done when creating, but not the first time something is edited.

To reproduce:

1. Create new item with valid values
2. Edit item, make one or more values invalid (e.g. −1 points) and save it
3. Item is saved with invalid values. Trying to edit it again at all shows the "invalid reward" error. (Expected: item isn't saved the first time invalid values are entered)

Also, creating/editing an item and failing (e.g. invalid value) should ideally show flash notice on that form page itself, but this isn't critical and can likely be easily fixed later. (i.e. optional fix, you don't need to do it now)

**Review by CerebralDatabank — APPROVED** [review]
Looks good! 😊

**Pull request merged**
