### PR TITLE
Created page and functionality for member's activity history.

### PR DESCRIPTION
**Pull request by jhbeeber**
Created a table in an .html.erb file that lists the activities that the current member has participated in and got points for. Also implemented some filters where the member can filter based on type of activity and the starting/ending date. The table does have some inline CSS in it to separate the buttons a little bit, but should be removed once it is merged with dev. Also added a security feature that prevents members from accessing others' history pages by changing the ID in the URL.

### CODE REVIEW

**Comment by jhbeeber** [comment]
Also, should I be doing something else to make sure the Rails checks/tests don't fail in GitHub?

**Comment by CerebralDatabank** [comment]
For the GitHub Actions error — maybe change what it says below?

image

I don't know if we should enable or disable all new cops by default though.

**Review by CerebralDatabank — CHANGES_REQUESTED** [review]
Looks great! Everything seems to work well, including filtering by activity type and date range.

One small thing: when a search is done, and it redirects to the same page with the URL params for search, the form fields should remain filled out for easy editing. (This can probably be accomplished by filling in the form fields with the values from the URL params if they exist.)

**Review by ShahirAliGit — APPROVED** [review]
lgtm, gonna piggyback off the code for admin

**Review by jaejin0 — APPROVED** [review]
I think the functionality, where we grab user_id from session and compare with the param id, should be implemented for other pages (or controller) as well.
Looking great! Imma approve it

**Review by CerebralDatabank — APPROVED** [review]
LGTM 👍

**Review by annapachecohartman — APPROVED** [review]
Great job!! I really like the filtering feature. Let's merge it!

**Pull request merged**
