### PR TITLE
Make sure `seeds.rb` doesn't make duplicates

### PR DESCRIPTION
**Pull request by CerebralDatabank**
Changed all commands in `seeds.rb` to only create a new entry if one does not already exist.

This PR only modifies the `db/seeds.rb` file.

### CODE REVIEW

**Review by jaejin0 — APPROVED** [review]
Good to see that I am not duplicated anymore! Imma approve it!

**Review by annapachecohartman — APPROVED** [review]
This is a pretty straightforward fix. Only thing is I would fix the rubocop offenses so that it passes Github Actions. LGTM.

**Review by jhbeeber — CHANGES_REQUESTED** [review]
Good change since we won't have duplications in our database anymore. Before merging, let's get the Rubocop tests passing so we don't have any issues later on with it.

**Comment by CerebralDatabank** [comment]
Fixed the Rubocop offenses, was just a quick change 👍

**Review by jhbeeber — APPROVED** [review]
Looks good!

**Pull request merged**
