### PR TITLE
developed member's view on their spend transaction history

### PR DESCRIPTION
**Pull request by jaejin0**
I developed based on Activity History because previous work on user-spend-txn-hist branch was difficult to merge with other branches.

### CODE REVIEW

**Review by jhbeeber — APPROVED** [review]
I am going to approve because by looking at it, it should work as intended. The only thing missing is the points attribute in spend transactions but that's already merged in the dev branch. Good job!

**Comment by jaejin0** [comment]
I added points attribute tot he spend transaction to the db/schema.rb

**Review by CerebralDatabank — APPROVED** [review]
Looks good! Of course, we'll still have to do some manual merging with the history tables later.

Also, maybe take a look at the failing RSpec/Rubocop tests as well — fixing it now will be easier than fixing it later :P

**Review by annapachecohartman — APPROVED** [review]
LGTM!

**Pull request merged**
