### PR TITLE
Documentation & support form

### PR DESCRIPTION
**Pull request by CerebralDatabank**
I added a documentation page at `/docs` which contains documentation for members and officers, as well as a link to a support form (Google Forms).

The max width of the text is set to be `800px`.

### CODE REVIEW

**Review by ShahirAliGit — APPROVED** [review]
Looks good on the documentation

**Review by annapachecohartman — APPROVED** [review]
Looks great! The text is well organized and readable

**Review by jaejin0 — APPROVED** [review]
The documentation looks great!

**Comment by CerebralDatabank** [comment]
Thanks guys! 👍

**Pull request merged**
