### PR TITLE
Mobile

### PR DESCRIPTION
**Pull request by ShahirAliGit**
Styles change between mobile and desktop

### CODE REVIEW

**Review by CerebralDatabank — CHANGES_REQUESTED** [review]
It looks like activity history's tables are not displaying correctly.

**Review by jhbeeber — APPROVED** [review]
LGTM!

**Comment by CerebralDatabank** [comment]
Looks good! 👍

Also, note that Shahir also changed the Assign Points page so that the whole user card is clickable to (un)check that user, not just the actual checkbox, to make the UI easier to use for desktop and mobile devices.

**Review by CerebralDatabank — APPROVED** [review]
Looks good! 👍

Also, note that Shahir also changed the Assign Points page so that the whole user card is clickable to (un)check that user, not just the actual checkbox, to make the UI easier to use for desktop and mobile devices.

**Comment by ShahirAliGit** [comment]
this was painful, everything fixed

**Pull request merged**
