### PR TITLE
Ability to grant members points for an activity in bulk.

### PR DESCRIPTION
**Pull request by annapachecohartman**
User story: "As an officer, I want to be able to grant members points for an activity in bulk, so I can quickly reward members at an activity without going through them one-by-one."
Implemented: points & handle_points actions in User controller, points page in User view. Only accessible to admin/officers. Able to connect with either a recurring activity or a one-time custom activity.

### CODE REVIEW

**Review by CerebralDatabank — CHANGES_REQUESTED** [review]
Great work! 👍 I tested all the functionality, and it works well (except for the range error below).

Some things to check though:

- When filling out a form and submitting, if the submission fails, it should stay on the form with all values still filled out and display the failure flash notice there (so the user can easily edit their values to valid ones).
- The two choices for activity shouldn't be displayed at the same time with "OR". There should be an option in the dropdown labeled "Custom" (or something similar). When that option is selected, the "Associated One-time Activity" field should appear, and when something else is selected, it should be hidden.
- The UI allows adding any amount of points (negative or positive), which shows a Rails error when the sum of the entered points and any user's current points is below $0$ or above $`2\,147\,483\,647`$.

  image

  Submitting a negative value within range successfully reduces a user's points. Given that it is probably desirable for admins to take away points (in case of a mistake), this can either be resolved by

  1. adding an explicit option on this page to *remove* points instead, and keep the input field in the range $`[0,\ \infty)`$ or $`[0,\ 2\,147\,483\,647]`$.
  2. having another page for removing points, again with the input field being restricted to positive numbers like above.

  If necessary, we can just add validation now (positive values only) and push the point removal to a later sprint. In any case, we should avoid the user seeing a Rails error message, and instead show a failure flash notice.

Also: I don't know how we should have the users be selected here. I was thinking more of a dropdown list that can be searched and users can be added, similar to Gmail, Zoom invite, Docs share menu, etc. Perhaps this is good for now though; a more complex solution would likely involve CSS styling as well.

**Comment by annapachecohartman** [comment]
I implemented a search bar, select/deselect all and show selected/all buttons, points validation, and fixed failure flash notices to stay on the same page.
image

**Review by jaejin0 — APPROVED** [review]
I tested the assign points page and worked well. I personally think, instead of having two buttons (Show Selected Users & Show All Users), it would be better to have one single switch button that switch between the two. I think it can be modified in later stage of development.
Looking great! Imma approve it.

**Comment by jaejin0** [comment]
Also, I just realized that we might want to add email or any other unique attribute, since we might have two person having the same name and accidentally give points to a wrong person.

**Comment by annapachecohartman** [comment]
> Also, I just realized that we might want to add email or any other unique attribute, since we might have two person having the same name and accidentally give points to a wrong person.

Great point!! I just replaced the point values next to the names with emails, and I figured out a way to get the buttons to toggle. Hopefully it's better now.

**Review by CerebralDatabank — APPROVED** [review]
I tested everything and it works well! Great job!

**Pull request merged**
