### PR TITLE
Transaction history for each user in the Admin view

### PR DESCRIPTION
**Pull request by CerebralDatabank**
Transaction history is shown in one table with both earn and spend transactions.

(This is shown in the user details page `/users/N`, which does not currently have a link in the UI.)

### CODE REVIEW

**Comment by CerebralDatabank** [comment]
Very simple for now, I'll probably have to merge this manually with the admin page and styling from #20.

**Review by jhbeeber — COMMENTED** [review]
I am having the same issue that you were having with the admin page being blank other than the signing out and view rewards links. Did you ever figure out what was going on with it or how to fix it?

**Comment by CerebralDatabank** [comment]
Yeah, it's just that the `dev` branch didn't have those changes when I branched off. I don't want to risk rebase or merge messing up anything, so I'll just re-branch-off and apply my changes again.

**Comment by CerebralDatabank** [comment]
@jhbeeber Note that the branch has been re-created, so please reclone.

The pages should show up properly now.

**Comment by CerebralDatabank** [comment]
Ok, *now* it should be ready 😂 I added code to make sure that it actually sorts via timestamps.

**Review by jhbeeber — APPROVED** [review]
Looks good to me. Hopefully it will be easy to combine our tables into this format.

**Review by annapachecohartman — APPROVED** [review]
Assuming this PR is just for displaying purposes, this is good.

**Review by jaejin0 — APPROVED** [review]

**Comment by CerebralDatabank** [comment]
Ok, should be ready now (again lol).

- Purchasing an item now creates a `SpendTransaction`
- `SpendTransaction` now has an integer `points` attribute, just like `EarnTransaction`

Some stuff will need to be fixed manually after this is merged (like the transaction tables), but that is outside of this PR's scope.

**Pull request merged**
