### PR TITLE
initialized functionality of member view

### PR DESCRIPTION
**Pull request by jaejin0**
[what are worked on members branch]
- created functionalities of members, such as viewing their info, deleting their account, and navigating to rewards page.
- modified omniauth_callbacks_controller to get a certain user entity from the user table using admin.email and pass as a parameter to member_dashboard_path
- modified the members' view of rewards page, such as memberindex, membershow, and purchase, as well as handle purchase action, to take user_id as parameters.

[what to improve]
once we login using one of the accounts, we can navigate to different users by simply changing the id parameter of url.

### CODE REVIEW

**Review by annapachecohartman — COMMENTED** [review]
Looks good!  When I committed changes, I removed the link to the edit page. I think it's kinda unnecessary since there's nothing that can really be edited other than the name. I also agree there's no need for new or index. But what do y'all think?

**Comment by jaejin0** [comment]
Great! The only thing mattered with edit page was a link to the delete page. And, since we commented the link out, I just added the link to the show.html.erb as well, so we are good!

**Review by annapachecohartman — APPROVED** [review]
I think we should go ahead and merge this branch now so Shahir can get started.

**Review by CerebralDatabank — COMMENTED** [review]
Lol too late now but looks good 👍 I changed `flash[:success]` to `flash[:notice]` because I think Rails only comes with `:notice` and `:alert` by default. Also, I removed the `.DS_Store` macOS file.

**Pull request merged**
